version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

[analyzers.meta]
max_line_length = 120
skip_doc_coverage = ["module", "magic", "init"]
additional_builtins = ["_", "pretty_output"]
type_checker = "mypy"

[[code_formatters]]
name = "ruff"
